import type { NarrativeEntry } from "@/types/common";

export const OPENING: NarrativeEntry[] = [
	{
		entry_id: "B1",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "当晚，实践驻地。",
		style: "narration",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "B2",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "有人还在核对文件，有人洗漱后已经休息。",
		style: "narration",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "B3",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: "房间里的风扇持续转动，吹得桌角的纸页轻轻颤动。",
		style: "narration",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "B4",
		kind: "dialogue",
		speaker_id: "CLASSMATE_DOOR",
		speaker_name: "门外同学",
		text: '"今天的材料你先整理着，我去还设备——"',
		style: "dialogue",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "B5",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "门外的脚步声远了。",
		style: "narration",
		cps: 14,
		advance: "manual",
		sfx: "footsteps",
	},
	{
		entry_id: "B6",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "房间里只剩你和一桌散开的纸张。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
];

export const AUDIO_REVIEW: NarrativeEntry[] = [
	{
		entry_id: "A1",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: "你戴上耳机，重新播放白天的采访材料。",
		style: "narration",
		cps: 14,
		advance: "manual",
		sfx: "tape",
	},
	{
		entry_id: "A2",
		kind: "sfx",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "录音里有风声、椅子腿蹭地声，偶尔还有实践队成员的提问。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "A3",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "受访者说话并不连贯。有时，一个地点刚刚被提起，叙述便转向另一个人；有时，话说到一半，对方会停很久，像是在辨认一段已经过去许多年的记忆。",
		style: "narration",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "A4",
		kind: "thought",
		speaker_id: "PLAYER",
		speaker_name: "心理旁白",
		avatar_id: "prologue-player",
		text: '"白天，这些只是需要编号、转写和核对的材料。到了夜里，沉默反而震耳欲聋。"',
		style: "thought",
		cps: 13,
		advance: "manual",
	},
];

export const WRITE_QUESTION: NarrativeEntry[] = [
	{
		entry_id: "W1",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: '你低头看实践笔记。"刘绍南"三个字下方，仍留有一大片空白。你想了想，提起笔，在空白处写下：',
		style: "narration",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "W2",
		kind: "write",
		speaker_id: "NOTE",
		speaker_name: "笔记",
		text: '"如果是我，在那个时候、那个地方——"',
		style: "thought",
		cps: 10,
		advance: "manual",
	},
	{
		entry_id: "W3",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: "笔尖停住。",
		style: "narration",
		cps: 9,
		advance: "manual",
	},
	{
		entry_id: "W4",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: "风扇吹动纸页，尚未干透的墨水在最后一笔处洇开一点。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "W5",
		kind: "thought",
		speaker_id: "PLAYER",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: '"我会做什么？是先弄清局势，还是先决定站在哪一边？如果身边还有许多人，我会相信谁，又该怎样让别人相信我？"',
		style: "thought",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "W6",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "问题越来越多，真正能写下来的答案却一个也没有。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "W7",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: "你本想再听一段录音。手指刚要碰到播放键，门外便传来同学的声音。",
		style: "narration",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "W8",
		kind: "dialogue",
		speaker_id: "CLASSMATE_DOOR",
		speaker_name: "门外同学",
		text: '"还没睡啊？"',
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "W9",
		kind: "dialogue",
		speaker_id: "PLAYER",
		speaker_name: "你",
		avatar_id: "prologue-player",
		text: '"快了。我把这页整理完。"',
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "W10",
		kind: "dialogue",
		speaker_id: "CLASSMATE_DOOR",
		speaker_name: "门外同学",
		text: '"别熬太晚，明天还要继续走访。"',
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "W11",
		kind: "dialogue",
		speaker_id: "PLAYER",
		speaker_name: "你",
		avatar_id: "prologue-player",
		text: '"知道了。"',
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "W12",
		kind: "sfx",
		speaker_id: "SFX",
		speaker_name: "音效",
		text: "门外的脚步声逐渐远去。",
		style: "narration",
		cps: 12,
		advance: "manual",
		sfx: "footsteps",
	},
	{
		entry_id: "W13",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "房间重新安静下来，只剩风扇、虫鸣和录音设备细微的底噪。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
];

export const FALL_ASLEEP: NarrativeEntry[] = [
	{
		entry_id: "S1",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: "你取下耳机，把笔横放在实践笔记上。困倦和纷乱思绪如潮水袭来，一波未平又复起。",
		style: "narration",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "S2",
		kind: "thought",
		speaker_id: "PLAYER",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: '"只是闭眼歇一会儿。"',
		style: "thought",
		cps: 11,
		advance: "manual",
	},
	{
		entry_id: "S3",
		kind: "scene",
		speaker_id: "STAGE",
		speaker_name: "画面",
		text: "你伏在桌边，额头贴上手臂。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "S4",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "粗糙的纸边轻轻擦过皮肤。白天积下的疲惫终于漫过那点勉强维持的清醒，桌上的文字也渐渐失去清晰的边界。",
		style: "narration",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "S5",
		kind: "thought",
		speaker_id: "PLAYER",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: '"最后只剩一个名字还在脑海里一遍一遍播放，刘绍南。"',
		style: "thought",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "S6",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "随后，连这个名字也沉进风扇单调的转动声里。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
];

export const TIME_TRAVEL: NarrativeEntry[] = [
	{
		entry_id: "T1",
		kind: "thought",
		speaker_id: "PLAYER",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "黑暗里，风扇的声音越来越远。",
		style: "thought",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "T2",
		kind: "thought",
		speaker_id: "PLAYER",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "有一只碗被轻轻放在桌上。",
		style: "thought",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "T3",
		kind: "thought",
		speaker_id: "PLAYER",
		speaker_name: "心理描写",
		avatar_id: "prologue-player",
		text: "门轴响了一声——不是驻地的那扇门。",
		style: "thought",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "T4",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "字幕",
		text: "1927年夏 · 洪湖 戴家场",
		style: "narration",
		cps: 8,
		advance: "manual",
	},
];

export const TASKS = {
	opening: {
		title: "整理今天的材料",
		detail: "听一遍采访录音，再把没写完的问题补完。",
	},
	afterAudio: {
		title: "整理今天的材料",
		detail: "录音听完了。把没写完的问题补完。",
	},
};

export const PROP_LINES: Record<string, Record<string, string>> = {
	notebook: {
		default: "摊开的实践笔记。没写完的问题还停在纸上，墨迹已经干了。",
		name_checked:
			'摊开的实践笔记。"刘绍南"三个字旁，留着白天核对过的记号。',
		name_written: '实践笔记摊开着，停在写有"刘绍南"的那一页。',
	},
	phone: {
		default: "手机屏幕暗着。白天走访拍下的照片还留在相册里。",
		monument_photo: "手机屏幕停在纪念碑的照片上——碑面的名字在取景框正中。",
	},
	recorder: {
		default: "采访录音设备。存储卡里是白天没听完的采访。",
		selected_file: "采访录音设备。光标预先停在涂老五那段采访文件上。",
	},
};

export const ONE_LINERS = {
	desk: "台灯还亮着。相机、镜头和散开的采访纸摊了一桌。",
	bed: "还不困。桌上的材料还没整理完。",
	exit: "今晚不出去了。材料还摊在桌上。",
	notebookBlocked: "先把采访录音听完，再动笔。",
	notebookRepeat: "问题还停在纸上。答案不在今晚。",
	recorderRepeat: "这段材料已经看过一遍了。",
	recorderRepeatSelected: "设备停在涂老五那段采访——已经听过一遍了。",
};
