import type { NarrativeEntry } from "@/types/common";

/** 第四章场景五：最终补写之后，答案从纸面回到玩家自身。 */
export const CH04_ANSWER_WRITTEN_NARRATIVE: NarrativeEntry[] = [
	{
		entry_id: "CH04_SC05_PEN_STOPS",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "无论你选择哪一项，笔尖都会在最后一个字后停住。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_NOTEBOOK_OPEN",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "你没有立即合上笔记本。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_FAN_MATERIALS",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "风扇仍在转动，桌边的材料被吹得轻轻颤动。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_ANSWER_COMPLETE",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "至此，你终于补完了序章留下的那句话。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_NOT_CHEN",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "它不是陈继南的回答。",
		style: "narration",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_NOT_HISTORICAL_QUOTE",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "不是戴安南、董云庭或者王爷庙前任何一个人的原话。",
		style: "narration",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_YOUR_ANSWER",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "而是此时此刻的你，能够写下的答案。",
		style: "narration",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_LIMIT_OF_ANSWER",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "这个答案不能替历史中的人解释他们为何行动，也不能预见历史后来的走向。",
		style: "narration",
		cps: 11,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC05_WHAT_TO_REMEMBER",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "它只能回答，当你再次回想起那个中秋月夜时，自己选择记住什么。",
		style: "narration",
		cps: 11,
		advance: "manual",
	},
];
