import type { NarrativeEntry } from "@/types/common";

/**
 * 第四章场景二：意识交错。
 *
 * 本段没有选项、没有数值变化，也不授予玩家新的行动权限；它只用固定
 * 镜头和对话推进完成从历史现场到穿越前状态的过渡。未知脑海声音不
 * 绑定头像，以保留“陈继南意识／身体残留记忆／玩家理解”三者未定的边界。
 */
export const CH04_CONSCIOUSNESS_NARRATIVE: NarrativeEntry[] = [
	{
		entry_id: "CH04_SC02_CROWD_PEAK_ASSOCIATION",
		kind: "cue",
		speaker_id: "CROWD",
		speaker_name: "群众声音",
		text: "“农民协会！”",
		style: "cue",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_CROWD_PEAK_SELF_DEFENSE",
		kind: "cue",
		speaker_id: "CROWD",
		speaker_name: "群众声音",
		text: "“自卫团！”",
		style: "cue",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_CROWD_PEAK_WORKERS",
		kind: "cue",
		speaker_id: "CROWD",
		speaker_name: "群众声音",
		text: "“工农当家！”",
		style: "cue",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_CROWD_OVERLAP",
		kind: "cue",
		speaker_id: "CROWD",
		speaker_name: "群众声音",
		text: "人群的声音逐渐重叠。声音越来越近，又越来越远。你听不清具体的人声，只能听见这几个词反复出现。",
		style: "cue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_IMAGE_UNSTABLE",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "固定场景仍然停留在王爷庙。但人群轮廓逐渐模糊，对联中的字出现短暂的错位，戏台上的人物不再清晰；远处的哨声和群众回应混在一起。",
		style: "narration",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_IMAGE_BOUNDARY",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "画面没有旋转，人物也没有飞散。只是原本清楚的细节，开始像隔着一层还未散去的热气。",
		style: "narration",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_LEAVE_PLACE",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		text: "你忽然意识到，自己正在离开这里。",
		style: "thought",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_NOT_LEAVE_TEMPLE",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		text: "不是离开王爷庙。",
		style: "thought",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_LEAVE_BODY",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		text: "是离开这具身体。",
		style: "thought",
		cps: 15,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_SENSATION_RECEDES",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		text: "脚下泥地的触感开始消失。烈日灼烧皮肉的热度，人群的高声呼喊，一点一点退到远处。",
		style: "thought",
		cps: 12,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_UNKNOWN_SEES",
		kind: "dialogue",
		speaker_id: "UNKNOWN_MIND",
		speaker_name: "脑海声音",
		text: "你看见了吗？",
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_NO_REPLY",
		kind: "thought",
		speaker_id: "PLAYER_THOUGHT",
		speaker_name: "心理描写",
		text: "你想要回答。但却没有声音从喉咙里出来。",
		style: "thought",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_UNKNOWN_SHOT",
		kind: "dialogue",
		speaker_id: "UNKNOWN_MIND",
		speaker_name: "脑海声音",
		text: "别只记住谁开了枪。",
		style: "dialogue",
		cps: 14,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_UNKNOWN_PAUSE",
		kind: "cue",
		speaker_id: "SFX",
		speaker_name: "停顿",
		text: "短暂停顿。",
		style: "cue",
		cps: 16,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_UNKNOWN_STAND_TOGETHER",
		kind: "dialogue",
		speaker_id: "UNKNOWN_MIND",
		speaker_name: "脑海声音",
		text: "要记住他们后来怎样站到了一起。",
		style: "dialogue",
		cps: 13,
		advance: "manual",
	},
	{
		entry_id: "CH04_SC02_AMBIGUOUS_MEMORY",
		kind: "narration",
		speaker_id: "NARRATOR",
		speaker_name: "旁白",
		text: "声音消失。你无法判断：这是陈继南留下的意识，是这具身体残留的记忆，还是你自己在离开前形成的理解。",
		style: "narration",
		cps: 12,
		advance: "manual",
	},
];
